
#1. 
CREATE DATABASE PROJECT;

#DROP DATABASE PROJECT;
show databases;


#3.
USE PROJECT;

#4. SHOW TABLES;
#5. CREATE A TABLE

CREATE TABLE MEMBERS
(
	MemberID		INT	NOT NULL,
	LastName		VARCHAR(15),
	FirstName		VARCHAR(15)	NOT NULL,
	CompanyID			INT	NOT NULL,
	PRIMARY KEY(MemberID),
	FOREIGN KEY(CompanyID) REFERENCES COMPANY(CompanyID)
);

CREATE TABLE ASSET
(
	AssetID     INT NOT NULL,
	AssetName   VARCHAR(15),
	AssetType   VARCHAR(15) NOT NULL,
	IP          VARCHAR(15) NOT NULL,
	AssetOwner  INT NOT NULL,
	PRIMARY KEY(AssetID),
	FOREIGN KEY(AssetOwner) REFERENCES MEMBERS(MemberID)
);

CREATE TABLE INCIDENT
(
	IncidentID		INT	NOT NULL,
    CompanyID INT NULL,
	Country		VARCHAR(15),
	Year		VARCHAR(20),
	ThreatType			VARCHAR(30)	NOT NULL,
    AffectedIndustry		VARCHAR(30)	NOT NULL,
    DataBreached VARCHAR(15),#In GB
    FinancialImpact VARCHAR(20), #In M
    SeverityLevel  VARCHAR(15),
    ResponseTime VARCHAR(15),
    MitigationStrategy VARCHAR(30),
    Company VARCHAR(15),
	Lat DECIMAL(9,6),
	Lng DECIMAL(9,6),
	PRIMARY KEY(IncidentID)
);

CREATE TABLE COMPANY
(
	CompanyID		INT	NOT NULL,
	CompanyName		VARCHAR(15),
	PRIMARY KEY(CompanyID)
);
#6. SHOW TABLES
SHOW TABLES;

DROP TABLE INCIDENT;